# -*- coding: utf-8 -*-
"""Flask Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MeVJcQGVI4W3BACiTbvWbDxmvAKBoq-o
"""

!pip install flask scikit-learn joblib ngrok

import flask
from flask import request, jsonify
import joblib
import numpy as np
from sklearn.datasets import load_iris

model_path = 'iris_model.pkl'

try:
  model = joblib.load(model_path)
except FileNotFoundError:
  iris = load_iris()
  X, y = iris.data, iris.target
  from sklearn.ensemble import RandomForestClassifier
  model = RandomForestClassifier()
  model.fit(X, y)
  joblib.dump(model, model_path)
  print(f'Model not found, trained and saved as {model_path}')

app = flask.Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
  if request.method =='POST':
    try:
      data = request.get_json()
      sepal_length = data['sepal_length']
      sepal_width = data['sepal_width']
      petal_length = data['petal_length']
      petal_width = data['petal_width']
      features = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
      prediction= model.prediction(features)[0]
      iris_names = load_iris().target_names
      result = {'prediction': iris_names[prediction].capitalize()}
      return jsonify(result)
    except Exception as e:
      return jsonify({'error': str(e)})

!pip install pyngrok
if __name__ =='__main__':
      from pyngrok import ngrok
      # Set your authtoken here
      ngrok.set_auth_token('2vxHLxahWJFaWVlYACGQ2ZS6PQT_7CcwbFx8HKhzVAmbbLsAN')
      port = 5000
      public_url = ngrok.connect(port).public_url
      print(f' * Running on {public_url}')
      app.run(debug=False, port=port)

