# -*- coding: utf-8 -*-
"""RandomForestClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mrAoY0Izsd3edlNwNYXJWlNT-VdVGhuf
"""

!pip install joblib

from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import joblib

iris = load_iris()
X, y = iris.data, iris.target

model = RandomForestClassifier()
model.fit(X,y)

joblib.dump(model, 'iris_model.pkl')

from google.colab import files
files.download('iris_model.pkl')