# -*- coding: utf-8 -*-
"""Streamlit code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/197vcUyL8Rg0zUBicGHyW_EdE8qKdJT0Z
"""

#Streamlit and flask

!pip install streamlit pyngrok

!pip install joblib
import joblib
import streamlit as st

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# import numpy as np

model = joblib.load('/content/iris_model.pkl')

st.title('Iris Flower Prediction')

sepal_length = st.number_input("Sepal length", min_value=0.0)
sepal_width = st.number_input("Sepal width ", min_value=0.0)
petal_length = st.number_input("Petal length", min_value=0.0)
petal_width = st.number_input("Petal width", min_value=0.0)

if st.button("Predict"):
  input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
  prediction = model.predict(input_data)
  st.success(f"The predicted class is: {prediction[0]}")

from pyngrok import ngrok

!streamlit run app.py &>/dev/null &



!ngrok authtoken 2vxHLxahWJFaWVlYACGQ2ZS6PQT_7CcwbFx8HKhzVAmbbLsAN
from pyngrok import ngrok
# Define the tunnel configuration with the 'addr' parameter
config = {
    "addr": 8501  # Specify the port using 'addr' for HTTP tunnels
}

# Connect to ngrok using the configuration
public_url = ngrok.connect( **config).public_url

# Print the public URL of your tunnel
print(f"Public URL: {public_url}")

